### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by Youjin1985** [frankie567/pwdlib#23]
```
from pwdlib import PasswordHash
password_hash = PasswordHash.recommended()
hash = password_hash.hash("herminetincture")
password_hash.verify("herminetincture", hash)  # True
```
result is:
`TypeError: PasswordHasher.hash() got an unexpected keyword argument 'salt'`

pwdlib.__version__: '0.2.1'
argon2.__version__: '21.3.0'

**Comment by Youjin1985** [comment]
works with argon2 '23.1.0'
